driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: fedora-25
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: default
  run_list:
  - recipe[auditd]

- name: rules
  run_list:
  - recipe[auditd::rules]

- name: stig-rules
  run_list:
  - recipe[auditd::rules]
  attributes:
    auditd:
      ruleset: "stig"

- name: capp-rules
  run_list:
  - recipe[auditd::rules]
  attributes:
    auditd:
      ruleset: "capp"
